Traceback (most recent call last):
  File "/home/sergio/.pyenv/versions/3.10.6/envs/mevolib_virt/bin/get_inference", line 8, in <module>
    sys.exit(main())
  File "/mnt/c/Users/sermo/tfg/MEvoLib/mevolib/inference/__init__.py", line 210, in main
    get_phylogeny(
  File "/mnt/c/Users/sermo/tfg/MEvoLib/mevolib/inference/__init__.py", line 162, in get_phylogeny
    output = subprocess.run(
  File "/home/sergio/.pyenv/versions/3.10.6/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/sergio/.pyenv/versions/3.10.6/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/sergio/.pyenv/versions/3.10.6/lib/python3.10/subprocess.py", line 1778, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
TypeError: expected str, bytes or os.PathLike object, not _TemporaryFileWrapper
